name: Mentionizer
markdown: redcarpet
pygments: true
baseurl: '/mentionizer'

exclude:
  - Gemfile
  - Gemfile.lock
  - bookmarklet.js

assets:
  css_compressor: sass
  baseurl: '/mentionizer/assets/'
  sources:
    - _assets/fonts
    - _assets/javascripts
    - _assets/stylesheets

